package es.spring.rest.persistence.curso;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import es.spring.rest.model.curso.Curso;
import es.spring.rest.model.curso.CursoExample;
import es.spring.rest.persistence.PersistenceBase;

public interface CursoMapper extends PersistenceBase<Curso, CursoExample> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_prueba
	 * 
	 * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
	 */
	int countByExample(CursoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_prueba
	 * 
	 * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
	 */
	int deleteByExample(CursoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_prueba
	 * 
	 * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_prueba
	 * 
	 * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
	 */
	int insert(Curso record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_prueba
	 * 
	 * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
	 */
	int insertSelective(Curso record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_prueba
	 * 
	 * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
	 */
	List<Curso> selectByExample(CursoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_prueba
	 * 
	 * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
	 */
	Curso selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_prueba
	 * 
	 * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
	 */
	int updateByExampleSelective(@Param("record") Curso record,
			@Param("example") CursoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_prueba
	 * 
	 * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
	 */
	int updateByExample(@Param("record") Curso record,@Param("example") CursoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_prueba
	 * 
	 * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
	 */
	int updateByPrimaryKeySelective(Curso record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_prueba
	 * 
	 * @mbggenerated Tue Oct 08 08:20:18 CEST 2013
	 */
	int updateByPrimaryKey(Curso record);
}
